spring:
  application:
    name: ms-proxy-gateway #指定服务名称
apollo:
  bootstrap:
    enabled: true
    namespaces: application,redis
    eagerLoad:
      enabled: true
  meta: http://192.168.3.21:8083
app:
  id: ${spring.application.name}